# Generated by Django 5.1.2 on 2024-11-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('rol', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=100)),
                ('contrasena2', models.CharField(max_length=100)),
            ],
        ),
    ]
