<<<<<<< HEAD
# Generated by Django 5.1.3 on 2024-11-28 13:43

import django.contrib.auth.models
=======
# Generated by Django 5.1.3 on 2024-11-27 15:10

>>>>>>> develop
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
<<<<<<< HEAD
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('userType', models.CharField(choices=[('admin', 'Admin'), ('client', 'Client')], max_length=10)),
                ('fullName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
=======
                ('username', models.CharField(max_length=150, unique=True)),
                ('userType', models.CharField(choices=[('client', 'Client'), ('admin', 'Admin'), ('staff', 'Staff')], default='client', max_length=150)),
                ('fullName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
>>>>>>> develop
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
<<<<<<< HEAD
                'db_table': 'users_perfil',
=======
                'abstract': False,
>>>>>>> develop
            },
        ),
    ]
