# Generated by Django 5.1.3 on 2024-11-26 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='name',
            new_name='fullName',
        ),
    ]
